const images = {
    logo: require('./logo.svg').default,
    avatar: require('./imgs/1.webp'),
    phahong: require('./imgs/phaohong.webp'),
    tongphu: require('./imgs/tongphu.webp'),
    yeulacuoi: require('./imgs/yelacuoi.webp'),
    huongly: require('./imgs/huongly.jpg'),
    mono: require('./imgs/bannerMono.jpg'),
    kim: require('./imgs/bannerKim.jpg'),
    chung: require('./imgs/chungDuy.jpg'),
    vpop: require('./imgs/vpop.jpg'),
    daivu: require('./imgs/daivu.jpg'),
    namcu: require('./imgs/5cu.webp'),
    sponsor1: require('./imgs/sponsor1.png'),
    sponsor2: require('./imgs/sponsor2.png'),
    sponsor3: require('./imgs/sponsor3.png'),
    sponsor4: require('./imgs/sponsor4.png'),
    sponsor5: require('./imgs/sponsor5.png'),
    sponsor6: require('./imgs/sponsor6.png'),
    sponsor7: require('./imgs/sponsor7.png'),
    sponsor8: require('./imgs/sponsor8.png'),
    sponsor9: require('./imgs/sponsor9.png'),
    sponsor10: require('./imgs/sponsor10.png'),
};

export default images;
